### ISSUE TITLE
Generic runtime-environment script

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-buildtools#10]
Hi John,

Hopefully the last issue for v1. In order to avoid a proliferation of runtime environment scripts among users, it is rather crucial to centrally provide a solution that allows to set-up the essential environment variables for all the repositories in the working area. Please find an example below. Far from being perfect it should be able to pick up new daq-compliant packages added to a super-project without modifications.

Cheers,
Alessandro

```sh
WORKAREA_ROOT=$(cd $(dirname ${BASH_SOURCE}) && pwd)
BUILD_DIR="${WORKAREA_ROOT}/build"
if [ ! -d "$BUILD_DIR" ]; then
   ### Take action if $DIR exists ###
   echo "WARNING: ${WORKAREA_ROOT} doesn't exist, run build and try again..."
   return
fi
function sanitize_path {
         p=""
         for d in "$@"
         do
            p="${BUILD_DIR}/${d}:${p}"
         done
         p=${p%?};
         echo $p
}
DAQ_APPS_PATHS=$(find build -type d -not -path '*CMakeFiles*' -name 'apps')
DAQ_LIB_PATHS=$(find build -type d -not -path '*CMakeFiles*' -name 'src')
DAQ_TEST_PATHS=$(find build -type d -not -path '*CMakeFiles*' -name 'test')

export PATH="$(sanitize_path $DAQ_APPS_PATHS):$(sanitize_path DAQ_TEST_PATHS):$PATH"
export LD_LIBRARY_PATH="$(sanitize_path $DAQ_LIB_PATHS):$(sanitize_path DAQ_TEST_PATHS):$LD_LIBRARY_PATH"
export CET_PLUGIN_PATH="$(sanitize_path $DAQ_LIB_PATHS):$CET_PLUGIN_PATH"
```

**Comment by bieryAtFnal** [comment]
I'd like to understand the need/desire to only run this script once in a given shell.  If that has to do with not adding tons of paths to LD_LIBRARY_PATH and CET_PLUGIN_PATH, I understand that (but I wonder why it is a concern).  Unfortunately, the mechanism that is currently used to avoid doing that prevents the addition of new packages to the work area from being transparently included.
I would like to do the following in a single shell session:

- run quick start
- setup the build environment
- build the base packages
- setup the runtime environment
- run an example app from the appfwk repo
- clone an additional repo into the work area
- re-setup the build environment script (if needed)
- rebuild the work area 
- re-setup the runtime environment 
- run an example app from the recently added repo

**Comment by bieryAtFnal** [comment]
Sorry, I meant to add that comment to Pull Request #11.  I can copy it over, if that would be helpful

**Comment by alessandrothea** [comment]
This seems the right place. I agree that being able to run it multiple times to update the environment is a requirement.
I have an example on how to do that, if it's helpful.
