### ISSUE TITLE
Calling `find_package(HighFive)` in two different repos causes failure

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#104]
Basically, if you have more than one repo in your working area whose CMakeLists.txt calls `find_package(HighFive)`, you'll get a build error. If you create an empty directory, you can see this simply by running the following script:
```

if [[ -n $( ls ) ]]; then
    echo "Directory needs to be empty. Returning..." >&2
    return 1
fi

git clone https://github.com/DUNE-DAQ/daq-buildtools.git -b dunedaq-v2.2.0
. daq-buildtools/dbt-setup-env.sh

mkdir daqbuild
cd daqbuild
dbt-create.sh dunedaq-v2.2.0

cd sourcecode
for pkg in cmdlib readout ; do
    git clone https://github.com/DUNE-DAQ/${pkg}.git -b dunedaq-v2.2.0
    sed -r -i '/daq_setup_environment/ a find_package(HighFive REQUIRED)' ${pkg}/CMakeLists.txt
done
cd ..

dbt-setup-build-environment
dbt-build.sh
```
where you can see that two unrelated repos are downloaded and have `find_package(HighFive REQUIRED)` added to their CMakeLists.txt file. You'll also see the error go away if you comment out the call to `find_package(HighFive REQUIRED)` in one of the repos.

**Comment by dingp** [comment]
Testing that this issue no longer exists with the Spack-based release. Closing it now.
