### ISSUE TITLE
use functions instead of aliases

### ISSUE THREAD

**Issue by ron003** [DUNE-DAQ/daq-buildtools#114]
I created a wrapper function to do all the steps necessary to checkout and build a subset of the DUNE-DAQ software. This function fails when the function tries to do dbt-setup-build-environment.
If I comment out the clone of the daq-buildtools repo and change the aliases to functions (by editing dbt-setup-env.sh) then the function works perfectly.
```
diff --git a/dbt-setup-env.sh b/dbt-setup-env.sh
old mode 100644
new mode 100755
index 6f97a36..76c08bb
--- a/dbt-setup-env.sh
+++ b/dbt-setup-env.sh
@@ -9,6 +9,8 @@ source ${DBT_ROOT}/scripts/dbt-setup-tools.sh
 add_many_paths PATH ${DBT_ROOT}/bin ${DBT_ROOT}/scripts
 export PATH
 
-alias dbt-setup-build-environment="source ${DBT_ROOT}/scripts/dbt-setup-build-environment.sh"
-alias dbt-setup-runtime-environment="source ${DBT_ROOT}/scripts/dbt-setup-runtime-environment.sh"
+#alias dbt-setup-build-environment="source ${DBT_ROOT}/scripts/dbt-setup-build-environment.sh"
+dbt-setup-build-environment() { source ${DBT_ROOT}/scripts/dbt-setup-build-environment.sh; }
+#alias dbt-setup-runtime-environment="source ${DBT_ROOT}/scripts/dbt-setup-runtime-environment.sh"
+dbt-setup-runtime-environment() { source ${DBT_ROOT}/scripts/dbt-setup-runtime-environment.sh; }
 echo -e "${COL_GREEN}DBT setuptools loaded${COL_NULL}"
```

I would rather push a branch than fork or post diffs

**Comment by alessandrothea** [comment]
Nice! I think @dingp has already given you write access. Please push your branch and make a PR at your earliest convenience.

**Comment by ron003** [comment]
I took the liberty to fix 2 additional things: 1) flushing in pytee needed when redirecting/piping output of  dbt-build.sh, 2) dbt-create.sh error of user uses CDPATH.

**Comment by alessandrothea** [comment]
Fix merged. Closing
