### ISSUE TITLE
Errors in `dbt-setup-build-environment` cause session to be ended

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/daq-buildtools#118]
Any error in `dbt-setup-build-environment` causes the session to be ended. Eg, running the script twice:

```
> dbt-setup-build-environment ; dbt-setup-build-environment
This script hasn't yet been sourced (successfully) in this shell; setting up the build environment
DBT_AREA_ROOT=/home/rodrigues/dune/daq/dunedaq-v2.4.0-testrels/dataformats-serde
Product directories /cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/releases/dunedaq-v2.4.0/externals /cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/releases/dunedaq-v2.4.0/packages
Products 
setup -B cmake v3_17_2
setup -B gdb v9_2
[ More setups trimmed ]
All setup calls on the packages returned 0, indicative of success
This script has been sourced successfully

ERROR: [03/29/21 16:29:36] [dbt-setup-build-environment.sh]:  This script appears to have already been sourced successfully. Returning...  
Connection to pplxint10.physics.ox.ac.uk closed.
```

or putting an incorrect ups product version in `dbt-settings`.

I assume the culprit is this line:

https://github.com/DUNE-DAQ/daq-buildtools/blob/0556be68d9bc6924b6987cff505df42df464b024/scripts/dbt-setup-tools.sh#L176

**Comment by alessandrothea** [comment]
Hm, I've just tried and I cannot reproduce this issue.

**Comment by alessandrothea** [comment]
Counter-order. Stoyan has shown me how to make it happen this morning.

**Comment by alessandrothea** [comment]
OK, it seems to be related to the conversion of `dbt-setup-build-environment` from an alias to a bash function, which confuses the error function. To be investigated

**Comment by jcfreeman2** [comment]
Handled by Alessandro via PR #129
