### ISSUE TITLE
Make clang-formatting code easier 

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#119]
@philiprodrigues pointed out that right now clang-formatting code is a bit onerous. We should investigate ways to make the process more streamlined. Probably a standalone script would be best, although one could also imagine a `--clang-format <package>` option to `dbt-build.sh` which would format the sourcecode for a given repo before performing a build.

**Comment by alessandrothea** [comment]
Hi @jcfreeman2,
One small request before closing this issue: can we make the diffs colored?
i.e. adding the `--color` option to `diff`?

**Comment by jcfreeman2** [comment]
Closing issue as I created `dbt-clang-format.sh` last May.
