### ISSUE TITLE
daq-buildtools as standalone application

### ISSUE THREAD

**Issue by Juravenator** [DUNE-DAQ/daq-buildtools#120]
In its current form, it would appear that the daq-buildtools are modeled after the python virtualenv system. One sources a script and it sets up environment variables that help you run/build your Python package.

The daq-buildtools are becoming much more feature rich however, with features more commonly found in tools such as Makefiles, Maven, Go, etc. such as building and formatting (#119) with more to come in future (#29).

Given their complexity, the other development tools listed above are standalone applications rather than bash scripts.
Benefits would include having a much richer programming environment available to write the daq-buildtools (for new features and code quality like the attempt at using bash 'safe mode' #95), being agnostic to the shell users use (#117), keeping your shell clean (env variables might not need to be set at all anymore), keeping your shell clean in case of errors (#118).

This also would bring the opportunity to make daq-buildtools a more streamlined solution like other tools (`[make, maven, go, ...] [init, build, test, help, vet, ...]`).

**Comment by alessandrothea** [comment]
Yes, indeed. In fact, the thought has been in the back of my mind for quite a while now.
The main reasons for not having started to look into an alternative are:
- UPS has always been deemed a temporary solution while other options are evaluated, e.g. SPACK.
  Unofrtunately that is taking more than we hoped for, but it's progressing nevertheless. AFAIK SPACK provides a number of features which are currently implemented in `dbt` and are likely not to be needed after the transition
- UPS is what has mostly modelled daq buildtools, the python environment has followed later. The UPS environment has a non negligible bash footprint, and also provides python, which is a bit of a chicken and egg problem if one has to rely on python when putting together the initial work area. 
Bottomline, even if well aware that `dbt` as collection of bash scripts is far from ideal, it has been considered an acceptable evil to get going while working on SPACK.

**Comment by alessandrothea** [comment]
On the other hand, if you have suggestions / see a clear way to restructure the tools within these constraints, and with the understanding that it may have be done again for SPACK, please don't hesitate.

**Comment by alessandrothea** [comment]
A brief summary of main components and constraints
- `dbt-setup-env.sh`: generic setup script, sets paths to the dbt installation and a few encyclopaedia variables. Not evident how to replace it with non shell scripts.
- `dbt-setup-*-environment`: these scripts load ups and python environments + set path to the local build area. Again, not evident how to replace them given the ties with ups environment
- `dbt-build.sh`: executable script with multiple functions. Could (should?) Be broken in subscripts. Straightforward to translate into another language (python?)
- `dbt-create`: to be continued

**Comment by jcfreeman2** [comment]
This will not happen.
