### ISSUE TITLE
Single argument to `--lint` not working

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#140]
If I try running
```
dbt-build.sh --lint dfmessages
```
(or `--unittest` for that matter) then I see 
```
Unknown arguments 'dfmessages' provided
```
whereas previously the `--lint` and `--unittest` arguments were capable of accepting the name of a single package to lint and/or unit test.

**Comment by philiprodrigues** [comment]
I just ran into this. `man getopt` says: "If the [long] option has an optional argument, it must be written directly after the long option name, separated by '=', if present", and indeed, `dbt-build.sh --lint=dfmessages` works for me. So maybe just the help text needs to be changed

**Comment by jcfreeman2** [comment]
Thanks @philiprodrigues . Just talked to Alessandro and his suggestion is that I just update the documentation and let people know they need to use an `=` from now on if they want to provide a package name to `--lint` and `--unittest`

**Comment by bieryAtFnal** [comment]
It would be great if the command-line help for dbt-build.sh somehow indicated that the equals sign is needed...

**Comment by jcfreeman2** [comment]
The next daq-buildtools' release's command line help will definitely match its command line behavior.
