### ISSUE TITLE
Warn developers of inconsistent build

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-buildtools#143]
Often cases that a developer might be using a pre-build DAQ package in UPS products area, while building its dependent DAQ packages in their local source code area.

This will likely have several results:

1. cmake fails at conf+gen stage, e.g. complaining about a target is no longer exist (if the updates in the checkout package removed/updated some targets);
2. build fails;
3. build succeeded, but the software produces unexpected behaviors;
4. build succeeds and software runs correctly (this happens to minor, localized non-invasive changes).

To help developer being aware of these potential problems, I suggest in `dbt-build.sh` and possibly in `daq-cmake` package, to implement checks and print warnings in this situation. Ideally, the script/daq-cmake should be able to check if a developer is building anything from source, while using any pre-built UPS packages which sits behind the build-from-source package in `build-order.cmake`. If true, print a warning message, and list the packages which should also be build-from-source.

**Comment by dingp** [comment]
This is still a nice feature to have. Recently I was called upon an issue exactly like that described here.

**Comment by jcfreeman2** [comment]
Closing this since we no longer use UPS.
