### ISSUE TITLE
Nightly build of daq-buildtools and daq-cmake shouldn't automatically be used for a work area just because the nightly build for other packages is used

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#154]
A rephrase of this is, "If you want to use the most recent build of DAQ readout packages, you shouldn't have to completely rely on the packages having been kept up-to-date that same day with the assumptions made by the DAQ build packages (`daq-buildtools` and `daq-cmake`).

Of course, this introduces some ambiguity. E.g., should developers who set up a work area expect the nightly build of the DAQ readout packages to build against the most recent frozen release of `daq-buildtools` and `daq-cmake`? Against their night-before-last builds? Something in between? Things to think about.

**Comment by dingp** [comment]
This was fixed a while ago. Tagged `daq-cmake` and `daq-buildtools` versions are used in nightly releases now.
