### ISSUE TITLE
Request for assistance in debugging an issue in finding a dfmodules python module when running integrationtests

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/daq-buildtools#157]
I would like to request a favor, and that favor is for someone look into why the first set of commands below results in an integration test that fails to find the dfmodules.data_file_checks python module, whereas the second set of instructions succeeds in finding that module.

The only difference between the instructions is the version of the _readout_ code, which seems like it should be completely independent.
Thanks!
Kurt

This fails:
```
cd <directory_above_where_you_want_the_new_v2.8_software_area>
source <your_general_software_area>/daq-buildtools/env.sh
dbt-create.sh -n N21-07-25 26JulWorkDir_N0725Base
cd 26JulWorkDir_N0725Base
#
cd sourcecode
#
git clone https://github.com/DUNE-DAQ/readout.git -b develop
cd readout; git checkout 9c8f56ab; cd ..
#
git clone https://github.com/DUNE-DAQ/dfmodules.git -b develop
cd dfmodules; git checkout 75ade6fa; cd ..
#
git clone https://github.com/DUNE-DAQ/minidaqapp.git -b develop
cd minidaqapp; git checkout d15da1f0; cd ..
#
cd ..
# 
dbt-workarea-env
pip install -U https://github.com/DUNE-DAQ/nanorc/archive/develop.zip
dbt-build.sh
# 
cd sourcecode/dfmodules/integtest
curl -o frames.bin -O https://cernbox.cern.ch/index.php/s/VAqNtn7bwuQtff3/download
pytest -s four_process_empty_run_test.py --frame-file `pwd`/frames.bin
```

This works:

```
cd <directory_above_where_you_want_the_new_v2.8_software_area>
source <your_general_software_area>/daq-buildtools/env.sh
dbt-create.sh -n N21-07-25 26JulWorkDir_N0725Base
cd 26JulWorkDir_N0725Base
#
cd sourcecode
#
git clone https://github.com/DUNE-DAQ/readout.git -b develop
cd readout; git checkout 13928cd3; cd ..
#
git clone https://github.com/DUNE-DAQ/dfmodules.git -b develop
cd dfmodules; git checkout 75ade6fa; cd ..
#
git clone https://github.com/DUNE-DAQ/minidaqapp.git -b develop
cd minidaqapp; git checkout d15da1f0; cd ..
#
cd ..
# 
dbt-workarea-env
pip install -U https://github.com/DUNE-DAQ/nanorc/archive/develop.zip
dbt-build.sh
# 
cd sourcecode/dfmodules/integtest
curl -o frames.bin -O https://cernbox.cern.ch/index.php/s/VAqNtn7bwuQtff3/download
pytest -s four_process_empty_run_test.py --frame-file `pwd`/frames.bin
```

**Comment by jcfreeman2** [comment]
This is an update, not a solution:

@bieryAtFnal   I'm able to recreate the problem (thanks for the very convenient scripts). 

The _immediate_ cause of the problem is that in this part of the `log_file_checks.py` file in integrationtest:
```
     for line in open(log_file_name).readlines():
          # The first two words in the line are the date and time, then the severity
          severity=line.split()[2]
```
there's an index out-of-range error, because the top line of the log file looks like this:
```
stat again
2021-Jul-26 16:20:48,606 LOG [std::shared_ptr<dunedaq::opmonlib::OpmonService> dunedaq::opmonlib::makeOpmonService(const string&) at /scratch/dev/sourcecode/opmonlib/include/opmonlib/OpmonService.hpp:66] SERVICE = file://info_dataflow_3334.json
2021-Jul-26 16:20:48,633 LOG [restCommandFacility::restCommandFacility(std::__cxx11::string) at /scratch/dev/sourcecode/restcmd/plugins/restCommandFacility.cpp:68] Endpoint open on: localhost:3334 host:rest://localhost port:3334
```
I added a couple more lines because those look the lines at the top of the "healthy" logfile from your commands which worked. I'm currently unclear why there's a `stat again` tacked on at the top of the logfile, but I'll investigate.

**Comment by jcfreeman2** [comment]
Thanks, Carlos. This is quite interesting. I reran the first of Kurt's scripts - which worked on mu2edaq13 - on lxplus7103, and this time got the index error. I double checked the commit hashes, and they were indeed the expected ones. 

I'll bring this up with Alessandro at Thursday's meeting, but the upshot seems to be that currently we can't guarantee that non-official-logging output won't appear in the logfile and thus break the assumptions made by the integrationtestcode.

**Comment by bieryAtFnal** [comment]
Hi guys,
Two comments...

1. I suspect that the "stat again" issue is related to the (otherwise independent) behavior that has been noticed on lxplus in which it takes a couple of attempts to run _nanorc_ before it works the first time in a new software area.  When that was happening to me, I noticed quite a few "stat again" messages in the logs.  Of course, that makes it all the more interesting to understand where the "stat again" messages are coming from, because maybe there is a way to avoid having "stat" run lots of times in various scenarios.
2. Would it be possible to update the integrationtest log-check functionality to handle/skip non-official-logging?

Thanks,
Kurt

**Comment by floriangroetschla** [comment]
Interestingly enough, after getting a copy of TRACE v3_16_02 (from [here](https://scisoft.fnal.gov/scisoft/packages/TRACE/v3_16_02/)) and doing a grep for "stat again" I get a hit:
```
TRACE/v3_16_02/include/TRACE/trace.h:2624:			fprintf(stderr, "stat again\n");
```
This seems highly suspicious to me.

**Comment by bieryAtFnal** [comment]
That's a great find, Florian. 
Now we know who to talk with to learn more (Ron).

**Comment by jcfreeman2** [comment]
Great catch @floriangroetschla

**Comment by jcfreeman2** [comment]
This was handled in two ways:
* integrationtest now doesn't always assume a line in a logfile has standard formatting (https://github.com/DUNE-DAQ/integrationtest/pull/4/)
* Ron verified "stat again" is benign multi-threaded/multi-process issue
