### ISSUE TITLE
Can't `dbt-workarea-env --force-ups-reload`

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/daq-buildtools#169]
```
> dbt-workarea-env --force-ups-reload
getopt: unrecognized option '--force-ups-reload'
```
Looks like the culprit is this line, where `refresh` should be changed to `force-ups-reload`:

https://github.com/DUNE-DAQ/daq-buildtools/blob/ecb5193eab010ceb60e5420e4d3876593f6b5ff0/scripts/dbt-workarea-env.sh#L9

**Comment by alessandrothea** [comment]
Ooops... damn it.
Fixed in `thea/169-bugfix`

**Comment by jcfreeman2** [comment]
Fixed with the merge of Alessandro's `thea/169-bugfix` branch
