### ISSUE TITLE
Issues with prompt rewriting when using Spack

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/daq-buildtools#192]
I found when following the instructions for v2.11.0 and the Spack build, that scrolling through the history would result in the first few characters of one of the previous commands getting "stuck" after the prompt. Commands still worked, but they would get a little mangled on the command line.

```
(dbt-pyvenv) [N22-04-22]  [eflumerf@ironvirt7 dev-v2.11.0]$ for file inls
```

Disabling the Python vEnv prompt (via `export VIRTUAL_ENV_DISABLE_PROMPT=1` gave the same result):
```
[N22-04-22]  [eflumerf@ironvirt7 dev-v2.11.0]$ for file incd ..
```

Disabling the Spack prompt by editing `dbt-setup-tools.sh` and removing the `-p` from the `spack env activate` line appears to resolve the issue.

**Comment by dingp** [comment]
Before we find a longer term solution, instead of modifying `dbt-setup-tools.sh`, one can remove the spack env prompt by `despacktivate` (alias to `spack env deactivate`) followed by `spack env activate <release-env-name> # for example, "dunedaq-v2-11-0"`

**Comment by eflumerf** [comment]
Deactivating pyvenv after the fact does not help
```
(dbt-pyvenv) [N22-04-22]  [eflumerf@ironvirt7 dev-v2.11.0]$ deactivate
[N22-04-22]  [eflumerf@ironvirt7 dev-v2.11.0]$ less /home/ls
```

**Comment by eflumerf** [comment]
https://github.com/spack/spack/issues/29881

**Comment by dingp** [comment]
@eflumerf Thanks for finding the issue. I've turned off the spack env name in prompt. We will add it back once the issue is resolved upstream.
