### ISSUE TITLE
Separate package versions from quick-start.sh into another file

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-buildtools#2]
Plan to have a versioned/tagged release manifest file to list all packages and their versions. 

By using this file, quick-start.sh does not need to change when we switched to new releases or newer software versions.

**Comment by dingp** [comment]
I was thinking it might be better to have this manifest file in a separate package. It defines all things you need in a DAQ release. So it's better to be decoupled from `daq-buildtools`. Otherwise, one would need a new tag of `daq-buildtools` for each new DAQ release.

So it's better to have this live outside of every functional package.

**Comment by jcfreeman2** [comment]
To follow up on a discussion Pengfei, Alessandro and myself had: we agreed that what should happen is that setup_build_environment be told what, exactly, to set up. Currently it just sets up a given set of packages whose versions and qualifiers are hardwired, but as we get new versions and new qualifiers that solution of course will no longer be acceptable. The simplest thing to do would be to pass it the manifest file to read.

**Comment by alessandrothea** [comment]
Superseded by #30?

**Comment by alessandrothea** [comment]
Closed by #42
