### ISSUE TITLE
Remove *.py extensions from scripts in UPS-based daq-buildtools

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#208]
Analogous to what was done in Issue #198 for the Spack-based daq-builtools

**Comment by jcfreeman2** [comment]
Addressed via the `ups_legacy` branch: https://github.com/DUNE-DAQ/daq-buildtools/tree/ups_legacy#readme

**Comment by dingp** [comment]
Created tag `v4.1.7` for `daq-buildtools`, and deployed it to cvmfs. Also move the link `latest` to `v4.1.7`.

`ups_legacy` will be a long-lived branch in the `daq-buildtools` repo.
