### ISSUE TITLE
Build new image for each nightly/release/release candidate uploaded on harbor

### ISSUE THREAD

**Issue by plasorak** [DUNE-DAQ/daq-buildtools#223]
We badly need a automated way to create an image everytime there is a nightly, a release candidate, or a release cut.
These images should go on harbor at NP04
Nighlties can be deleted, of course, after they expire in 14 days.

**Comment by plasorak** [comment]
Also, it'd be good to come up with a naming convention and a web page which has all the nightlies listed (I think the admin pages of Harbor achieve this, but they have too much permissions for a developper).

**Comment by dingp** [comment]
I think this is completed with the new script (`dbt-setup-release-env.sh`) loading running environments deployed to cvmfs.

@plasorak Can we close the issue?

**Comment by plasorak** [comment]
Yes
