### ISSUE TITLE
Update clonevirtualenv.py to remove the use of deprecated `distutils` module

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-buildtools#224]
In the gcc-12 build of the release, we switched to a newer python version (3.10.4). As a side-effect, when running `dbt-create` with the `-c` option to clone the python virtual env, one will get the following warning message:

```
/cvmfs/dunedaq.opensciencegrid.org/tools/dbt/v6.0.0/scripts/../bin/clonevirtualenv.py:13: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.dir_util
```

The solution is to replace the usage of `distutils` by another module.

**Comment by eflumerf** [comment]
This looks fixed to me, at least I didn't get the error when I tried it again.
