### ISSUE TITLE
use clone venv option by default with dbt-create

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-buildtools#227]
The planned change will be:

1. `dbt-create` will have `-c` enabled by default (clone python venv from cvmfs to workarea);
2. add a new option, e.g. `-i`, for explicitly saying install the venv via pip;
3. add a second new option to specify the source of the pip install, whether its DAQ's pypi-repo on cvmfs, or PyPI and GitHub on the internet.

**Comment by jcfreeman2** [comment]
This was handled with the release of `v6.0.5` so I'm closing it.
