### ISSUE TITLE
`dbt-build --lint` not working

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#229]
In a nutshell, it appears that at some point setting up the DUNE DAQ environment stopped giving us `llvm` - i.e., if you take a recent work area and do 
```
dbt-workarea-env
spack find llvm
```
...then `llvm` isn't found, which means that linting (which uses `clang`) can't be performed.

**Comment by dingp** [comment]
Per discussion in the sw-coordination slack channel, we will have a separate spack instance with `llvm` installed.

`dbt` will need to set up that additional instance before doing linting.

`dbt-workarea-constants.sh` may have one additional env recording the path to the spack instance with `llvm`.

**Comment by jcfreeman2** [comment]
`dbt-build --lint` _is_ now working.
