### ISSUE TITLE
`dbt-build` from anywhere

### ISSUE THREAD

**Issue by plasorak** [DUNE-DAQ/daq-buildtools#235]
Is there any reason why `dbt-build` wouldn't be executable from anywhere after `dbt-workarea-env`? This would speed up some of the development (for me at least), not having to `cd ${DBT_AREA_ROOT}` every time would be handy.

**Comment by alessandrothea** [comment]
Yes, the reason is that `dbt` and the `dbt-*` commands are not tied to specific workares.
What may be possible instead is adding a `dbt-build` option to build from a specific directory, allowing, for instance, 
`dbt-build -d ${DBT_AREA_ROOT}`

**Comment by jcfreeman2** [comment]
I haven't heard a great clamor for this feature in the last nine months, so I'm closing the issue.
