### ISSUE TITLE
Minor rebuild problems with missing `build/` dir

### ISSUE THREAD

**Issue by brettviren** [DUNE-DAQ/daq-buildtools#24]
I went to rebuild and started by nuking the `build/` dir and then:

```
[s]bv@haiku:~/dev/dune-daq/sing> ./build_daq_software.sh --install
Expected build directory /home/bv/dev/dune-daq/sing/build not found; exiting...
```

Mainly, I document that I can simply `mkdir build` and get on with my life but then I see:

https://github.com/DUNE-DAQ/daq-buildtools/blob/develop/bin/quick-start.sh#L240

Seems like it's maybe best to just remove this "check" but maybe I miss something subtle.

**Comment by jcfreeman2** [comment]
If you want to do a ground-up build of appfwk, you just need to add the `--clean` option to ./build_daq_software.sh, e.g.:
```
./build_daq_software.sh --clean --install
```
Where `--clean` blows away the contents of `./build/appfwk`, or if you've selected a different repo to build via the `--pkgname` option, the contents of `./build/<your package>`, before proceeding with the rebuild.

**Comment by alessandrothea** [comment]
Is this still an outstanding issue or can it be closed?

**Comment by dingp** [comment]
Closing the issue. I think the `--clean` option in recent `dbt` for blowing off previous build (and installation) has been working fine.
