### ISSUE TITLE
Adding a new utility script `dbt-info` 

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-buildtools#246]
While implementing several convenience functions as found in #244, I realized it is better to create a `dbt-info` python script to do those things in one place, and provide more functionalities. Users can use it to get information on :
* DAQ release: (this is currently done via `dbt-release-info`, without displaying release path)
  - release type
  - release name
  - base release name
  - release path on cvmfs
* DAQ package: (this is currently done via `dbt-pkg-info`, but for a given package only)
  - version and commit hash for a given package or all packages;
  - installation path of a given package or all packages;
* external packages:
  - version and installation path of a given or all external packages;
* python modules:
  - list of all python modules and their versions
  - a given python module's version
* source repository checked out into `<workarea>/sourcecode`
  - name of the checked-out branch
  - if local changes exist
  - display local changes (wrapping around `git diff`)

We may add more functionalities to `dbt-info` in the future. 

Having a single python script `dbt-info` with well defined helper for getting information related to the workarea or a loaded release would very handy.

**Comment by alessandrothea** [comment]
Excellent idea!

**Comment by jcfreeman2** [comment]
Closed with https://github.com/DUNE-DAQ/daq-buildtools/pull/249
