### ISSUE TITLE
dbt-create -s issues with ~/.spack

### ISSUE THREAD

**Issue by ron003** [DUNE-DAQ/daq-buildtools#270]
Having a ~/.spack could (likely) cause dbt-create -s not to work.
Suggest having dbt-create -s and env.sh set SPACK_DISABLE_LOCAL_CONFIG=true

**Comment by eflumerf** [comment]
Additionally, a message about the presence and possible interference from ~/.spack might be a good idea

**Comment by alessandrothea** [comment]
I second that! I got tricked more than once by `~/.spack`

**Comment by andrewmogan** [comment]
Closed with PR #272
