### ISSUE TITLE
Allow simultaneous builds of multiple repositories

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#28]
Myself, Alessandro and Pengfei all agree that we need to scale up from the current model where `build_daq_software.sh` can only build a single package per call, and instead have it by default build _all_ the repositories which have been cloned into the development area. "default" means, if you don't supply `--pkgname <specific package you want to build>` it will build everything. Note that this is different than the current default behavior, where **appfwk** is built, and no other package. Relatedly, Alessandro would like to remove the feature whereby `quick-start.sh` automatically clones the **appfwk** repo; instead, **appfwk** should be treated as an equal with other repositories. 

Requirements for this feature include:
-In `CMakeLists.txt`, `find_package(your_dependent_package)` should pick up a local repo's code if it exists; otherwise, it should pick up an installed package. 
-By the same philosophy, the applications/libraries built off a repo should take priority over the applications/libraries in an installed package in the development area, even if the repo and the package both have the same ostensible version listed.

**Comment by alessandrothea** [comment]
Closed by PR #31
