### ISSUE TITLE
A script should generate a skeleton CMakeLists.txt file

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#29]
Currently, the best method to start developing your own DUNE DAQ package involves copying `toylibrary/CMakeLists.txt` from **daq-buildtools** to your new repo, and deleting the `add_library` and `add_executable` calls so you can add your own (https://github.com/DUNE-DAQ/appfwk/wiki/Instructions-for-creating-a-new-package). It would be even better if a script were provided which could just provide the skeleton  without references to **toylibrary** code, but off of which the **toylibrary** `CMakeLists.txt` file (or any other standard DUNE DAQ `CMakeLists.txt` file) could be edited.

**Comment by dingp** [comment]
Assigned this to `3.1.0` release. It's still nice to have this tool around.

**Comment by jcfreeman2** [comment]
Closing this as this functionality is a subset of what `create_dunedaq_package` supplies.
