### ISSUE TITLE
Look into separating setup_build_environment and build_daq_software.sh files from quick-start.sh

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#30]
The fact that `setup_build_environment` and `build_daq_software.sh` are both defined inside of `quick-start.sh` makes `quick-start.sh` hard to read. While this approach allows `quick-start.sh` to edit these scripts so, e.g., they know what the base directory is, this could also be accomplished, e.g., through sed commands applied to those scripts which are separate to begin with. It's worth looking into this approach.

**Comment by alessandrothea** [comment]
Closing, as PR#42 is merged.
