### ISSUE TITLE
Remove hard-coded install/build paths from cmake daq environment

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-buildtools#35]
Hi @alessandrothea.  Please note:

``` cmake
  set(CMAKE_PREFIX_PATH ${CMAKE_SOURCE_DIR}/../build ${CMAKE_SOURCE_DIR}/../install )

  set(CMAKE_INSTALL_LIBDIR ${PROJECT_NAME}/${CMAKE_INSTALL_LIBDIR})
  set(CMAKE_INSTALL_BINDIR ${PROJECT_NAME}/${CMAKE_INSTALL_BINDIR})
  set(CMAKE_INSTALL_INCLUDEDIR ${PROJECT_NAME}/${CMAKE_INSTALL_INCLUDEDIR})
```

Are all are non-standard patterns and will defeat standard CMake installation.

`CMAKE_PREFIX_PATH` should be set externally and if it must be set internally it should be added to, not reset.  (Or, is this also a "cumulative" setting?)

`CMAKE_INSTALL_PREFIX` should also be set externally and then CMake automatically follows it.

Instead of breaking standards by assuming some kind of source and installation layout, each package should have its `CMakeLists.txt` be stand-alone with these externalities unspecified.

Then a dev environment can be trivially created with a top-level `CMakeLists.txt` file like:

``` cmake
cmake_minimum_required(VERSION 3.12)
project(mydev)
add_subdirectory(appfwk)
add_subdirectory(listrev)
```
And, the developer has these easy commands:

``` cmake
$ export CMAKE_PREFIX_PATH=....
$ cmake -B build -S . -DCMAKE_INSTALL_PREFIX=/my/install 
$ cmake --build build -j$(nproc)
$ cmake --build build -t install
$ cmake --build build -t clean
```
If there is reason to use the source/install patterns currently baked in to the CMake in this branch, they can still be expressed by filling in the two `CMAKE_` env vars above.  Since we have a script-based install/development, this would be very natural.  The script could even manage creation and updating of the top-level `CMakeLists.txt` file.

PS: unrelated, but at this weeks HSF packaging working group meeting I learned we should be "spelling" all our minimum required cmake version lines with a range of versions like:

``` cmake
cmake_minimum_required(VERSION 3.4...3.12)
```

_Originally posted by @brettviren in https://github.com/DUNE-DAQ/daq-buildtools/issues/27#issuecomment-702737715_

**Comment by alessandrothea** [comment]
Related to #26 (possibly)

**Comment by brettviren** [comment]
> Related to #26 (possibly)

Circumstantially, yes.  Spack assumes developers follow best practices.

As-is, we are requiring our packages to to sit in an invented file system pattern when we try to build them.  This invention breaks best practicies and will require growing layers of scripting to support.

With less scripting and less CMake boilerplate we could instead make our packages follow best practices and still **allow** this invented file system pattern while not **requiring** it.

I don't see any reason to put off doing things correctly especially when it makes the CMake files simpler.

After all, isn't that the whole point of #27.

**Comment by alessandrothea** [comment]
#27 focusses on the package `CMakeList.txt`, trying to reduce the amount of cmake code package developers have to write. This issue (#35) wants to deal with how local paths are handled in `DAQ.make` such that each package can be either built with daq-buildtools or in standalone.

Being pragmatic, is it correct to state that the immediate concern is ensuring that `CMAKE_INSTALL_PREFIX` is respected?
i.e. that each package, installs its products in `${CMAKE_INSTALL_PREFIX}`? e.g. taking the example of `toyLibrary`

```
${CMAKE_INSTALL_PREFIX}/lib64/libtoylibrary.so
${CMAKE_INSTALL_PREFIX}/lib64/cmake/toylibraryTargets.cmake
${CMAKE_INSTALL_PREFIX}/lib64/cmake/toylibraryTargets-noconfig.cmake
${CMAKE_INSTALL_PREFIX}/include/toylibrary/IntPrinter.hpp
${CMAKE_INSTALL_PREFIX}/include/toylibrary/ValueWrapper.hpp
${CMAKE_INSTALL_PREFIX}/include/toylibrary/detail/ValueWrapper.hxx
${CMAKE_INSTALL_PREFIX}/lib64/cmake/toylibraryConfigVersion.cmake
${CMAKE_INSTALL_PREFIX}/lib64/cmake/toylibraryConfig.cmake
```

As things stand now, the support for multi-package builds has been introduces by PRs #31 and #33, and the support for setting the installation path from env/commandline by #26.

**Comment by brettviren** [comment]
@alessandrothea  

> Being pragmatic, is it correct to state that the immediate concern is ensuring that CMAKE_INSTALL_PREFIX is respected?

Yes, I think that's about half of the story. The other is to rely on the user (human or script) giving `CMAKE_PREFIX_PATH` env. var. to specify where dependencies live and not attempt to construct those locations in our CMake files.

In your example `CMAKE_INSTALL_PREFIX` tree, I don't think we need to specify sub-paths like `/include/` or `/lib64/` explicitly.  The latter, for example is OS-specific.  CMake should do the right thing and we shouldn't get in its way.

It seems "do the right thing" is controlled by https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html and indeed that is activated already in daq-buildtools!

**Comment by alessandrothea** [comment]
OK, `thea/i35-paths` should be ready for review. Pull request coming up...
