### ISSUE TITLE
daq_install() should handle the case where nothing's going to be installed

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#44]
Right now, if a package doesn't install any of its targets (e.g., because a user's for whatever reason commented out sections of their CMakeLists.txt which build installable targets), `daq_install()` will cause the build to fail with a hard-to-understand error, e.g.:
```
-- Configuring done
CMake Error: INSTALL(EXPORT) given unknown export "cmdlibTargets"
-- Generating done
```
(where for the example I intentionally commented out parts of cmdlib's CMakeLists.txt file). We should either cause `daq_install()` to be a no-op, or have it fail with an error message people can understand.

**Comment by dingp** [comment]
Closing this issue as PR#48 has been merged.
