### ISSUE TITLE
`$can_unbuffer` used uninitialized in `build_daq_software.sh`

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/daq-buildtools#52]
The `$can_unbuffer` variable is set inside the `if ! [ -e CMakeCache.txt ]` block, but is used after that block, so on runs where `CMakeCache.txt` already exists, this line:

https://github.com/DUNE-DAQ/daq-buildtools/blob/add19801fb70bd8f3c6aa64684770f08cca40641/bin/quick-start.sh#L354

uses `$can_unbuffer` unitialized. This works when `unbuffer` is available (because `if $undefined_variable` evaluates to true (TIL)), but not when `unbuffer` is not available. Moving the setting of `$can_unbuffer` so it happens unconditionally fixes the problem for me.

(Maybe it would also be useful to add `set -u` to the top of the script to catch other errors of this class in future)

**Comment by jcfreeman2** [comment]
Moved the can_unbuffer setting to outside the if-block. I'll look into `set -u`; however there are other places in the code where I use something like the `if [[ -z $var ]]; then blah` idiom instead of the `if [[ $var == "obviously meaningless value ]]; then blah` idiom
