### ISSUE TITLE
Need zmq UPS product for IPM

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/daq-buildtools#62]
A release of IPM is imminent, and it depends on the zmq UPS product. Users should be able to build and run IPM without having to manually add zmq to their test release. My PR which would have achieved this was merged then reverted. How is this going to be handled?

**Comment by dingp** [comment]
Hi Phil,

Before Alessandro got a chance to comment, I created a soft link to zmq to that under products_dev as a temporary solution. The move to products_dev now becomes transparent.

Best,
Pengfei

On Nov 25, 2020, at 5:24 AM, Philip Rodrigues <notifications@github.com> wrote:

﻿

A release of IPM is imminent, and it depends on the zmq UPS product. Users should be able to build and run IPM without having to manually add zmq to their test release. My PR which would have achieved this was merged then reverted. How is this going to be handled?

**Comment by philiprodrigues** [comment]
Thanks Pengfei. The other thing that is needed for IPM to be usable without fiddling on the part of users is to add zmq to the list of packages in `dunedaq_area.sh`

**Comment by alessandrothea** [comment]
Hi Phil, so manually fiddling with the dev-area configuration every time is non-optimal.
At the same time there must be a way to stage the requests for new packages to avoid inflating the product pool, and this is why we decided to add new products to the pool and `dunedaq_area.sh` only for new releases.
I understand this feels a bit odd for `ipm`+`zmq` which are going to be soon integrated, but this sort of issue is likely to pop up a number of times, so this seems a good opportunity to try understanding what would be a reasonable solution that serves both needs.

These are the options I can think about
1. Manual workarea editing (status quo): the local `.dunedaq_area` file is modified after the dev area is initialized. Has to be repeated for each newly created work area. Would be useful to understand the level of pain implied for the developer from 1 to 10.
1. Extending quick-start command line to 
   1. enable the dev pool
   1. add custom products 
  such that it could be possible to invoke it as
   `quick-start.sh --dev --add-ups="zmq:xx:yy"
  In this schema `--dev` would add `product_dev` and `zmq` to the enabled pools and list of packages respectively in `.dunedaq_area`
1. Introduce a pre-release...ahem... release where 
    - The dev pool is activate by default
    - Requests for candidate new packages for the next release can be easily accommodated for later review
    This makes use of the recent factorization done #70 
    A possible downside of this approach is that all one would not get just his own new dependencies, but all the whole set of new dependencies requested by any developer towards the next release.

@philiprodrigues Thoughts? Comment? Other ideas?

**Comment by philiprodrigues** [comment]
For the status quo, the per-package, per-working-area pain is low, but then it has to be multiplied by n_packages (go look at the website for each package to see what extra ups products it needs) and by n_working_areas, so it doesn't scale very well.

Is there a reason that we don't just move the list of each package's ups product dependencies to the package itself? This is parallel to how we `find_package(...)` the dependencies in the `CMakeLists.txt` of each package. And it means that `daq-buildtools` doesn't need to know about the dependencies of every possible package that could be built with it, so the approach should scale better. The most straightforward way I can think of for doing this would be to have a `.dunedaq_area` file in each package specifying that package's ups product dependencies, and have `setup_build_environment` loop over those files.

**Comment by brettviren** [comment]
The "official" build/user/dev/release ecosystem is becoming very elaborate and complicated to follow and since this ticket is broadened to a larger scope, I have just one self-preservation request:  

Please continue to retain layering so that at the lower layer any individual package can be `git clone`'d, and built in standard `cmake` ways specifically without relying on UPS patterns or requiring custom scripting or other patterns outside the package itself. 

If this core layer is retained, I can continue to not worry about whatever layers are being put on top and I can continue to rely on my dead simple `spack view` areas to develop and run various combinations of our packages.

(Frankly, I think `spack` negates the need to invent higher layers, but maybe I miss something)

**Comment by alessandrothea** [comment]
@philiprodrigues mostly because that would effectively mean inventing our own package dependency system layer, which is a decision that shouldn't be taken lightly, as it involves dealing with conflicts, overlaps and such.

The plan is still to evaluate spack and the hope is that it would fit the bill. Unfortunately it's taking a little longer than expected to get going with the evaluation.
Meanwhile we're the idea is to provide pain mitigation measures for a reasonable amount effort, like the ones I have outlined above.

**Comment by philiprodrigues** [comment]
I don't think we need to invent our own package dependency layer to do this. ups will already complain if asked to set up conflicting versions of products, so `setup_build_environment` will fail. In the case of conflicting ups products specified by two DAQ packages, the user has to do some manual work to fix it, but that's manual work that would equally have to be done in the existing `.dunedaq_area` setup. And in the per-package approach, the user who does the manual fix can immediately commit it, to make it available to everyone else.

**Comment by alessandrothea** [comment]
Hm, does UPS really complain? A very basic check like
```
>  setup sqlite v3_26_00_00
>  setup sqlite v3_32_03_00
>  setup sqlite v3_26_00_00
```
results in no warning whatsoever that a different version was already loaded.

**Comment by philiprodrigues** [comment]
Ah, good catch. I did a bit of digging and it turns out that setup with the `-B` flag will do "strict dependency" checking (see https://cdcvs.fnal.gov/redmine/projects/ups/wiki/Getting_Started_Using_UPS#Strict-Dependencies-B-flag ). Then:

```
> setup -B sqlite v3_32_03_00
> setup -B sqlite v3_26_00_00
Error encountered when setting up product: sqlite
ERROR: Version conflict -- dependency tree requires versions conflicting with current setup of product sqlite: version v3_26_00_00 vs v3_32_03_00
```
