### ISSUE TITLE
Factoring UPS and Python package lists from daq-buildtools

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-buildtools#70]
The code-reorganisation carried out for `v1.3.0` has made the first step towards decoupling the build tools from daq software releases by separating the list of release UPS packages from `quick-start.sh` into a dedicated file (`configs/dunedaq-area.sh`). Python was introduced at the same time in the release, and so the corresponding requirements file  (`configs/pyenv_requirements.txt`).

The next step towards separating `daq-buildtools` from specific release details are
- modify `quick-start.sh` to let the user select the daq release to use from command line.
- move those the "release" files out of this repo and in a place accessible by quick-start.

**Notes**
- The natural choice for storing the release files is cvmfs (where daq ups products are already)
- It must be possible to easily specify the chosen release (e.g, `quick-start.sh dunedaq-v2.0.0`) without having to specify the full path
- but the option to use a different base path should be provided.
- a way to print the list of available releases must be provided (e.g. `quick-start.sh --list`)

**Comment by alessandrothea** [comment]
Proof-of-principle of modified `quick-start.sh` is available in `thea/factoring-package-lists` branch.

Here a short summary of the changes
```
quick-start.sh -r/--release-path -d/--dir -l/--list <release name>
```
Where:
- `release-name`: is the name of the release the new work are will be based on (e.g. `dunedaq-v2.0.0`)
- `-r/--release-path`: is the path to the release archive (`RELEASE_BASEPATH` var; default: `/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/releases-tmp`)
- `-d/--dir`: is the path of the new area (`BASEDIR`var; default `$PWD`, the directory must exist)
- `-l/--list`: show the list of available releases
```

The first 3 arguments/options are self-explanatory as they basically set script parameters.
`--list` deserves a few words of explanation:
- It stops after showing the list of releases
- it automagically determines what is a valid release by looking into `RELEASE_BASEPATH` for subdirectories containing a `dunedaq_area.sh`. This is a way to do it, there are surely others. Even if it is adopted, the implementation should be reviews/improved (I expect `dunedaq_area.sh` to bre replaced by a proper manifest file, for starters)

**Comment by jcfreeman2** [comment]
Closed since corresponding PR 71 was merged into develop earlier today.
