### ISSUE TITLE
Factorise package build order from superproject's CMakelist.txt

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-buildtools#74]
After moving package lists from `daq-buildtools` repo into the release description (#70), the only remaining tie between `daq-buildtools` and the the release content is the package build order in `configs/CMakeLists.txt`, the superproject `CMakelist.txt`. Breaking this last tie will  make `daq-buildtools` completely release agnostic, so it seems a good idea to do that.

The first idea that comes to mind is moving the build-order list to a separate build-order file which is loaded by `CMakeLists.txt`. The build-order file becomes part of the software release, like `dunedaq_area.sh` and `pyvenv_requirements.txt` and is copied made available locally by `quick-start.sh`.

The build-order can be stores in plain text format or as a mini cmake-module, like 
```cmake
set(build_order "daq-cmake" "logging" "cmdlib" "restcmd" "appfwk" "ipm" "driver" "udaq-readout" "ddpdemo" "listrev")
```

and importing it into the superproj `CMakeLists` as
```cmake

...
include(DAQTopprojHelpers)

# Load build_order variable from file
include(.dbt-build-order.cmake)
...
```

I have given this option a try in the `thea/factoring-build-order` branch and it seems to work.
I wonder if it's worth trying the plain text file option as well or other solution I haven't thought of?

@jcfreeman2 @dingp Comments? Thoughts?

**Comment by jcfreeman2** [comment]
I think it makes sense for it to be a CMake module, unless there's a scenario we can think of where we could benefit from it just being a text file. One thing I'd add is, given that this is a file developers would likely want to edit, I think the negatives of hiding it with a "." (all those "where's the file where I can edit the build order?" emails from people who can't be bothered to RTFM) outweigh the positives.

**Comment by alessandrothea** [comment]
Ah, yes indeed. Actually, in there is a missing `/` in my previous message (cut & paste gone wrong).
The file is supposed to be named `dbt-build-order.cmake` and be located in the same folder as `CMakeLists`, thereby requiring the leading `./`. Then the `/` got lost...
```cmake
# Load build_order variable from file
include(./dbt-build-order.cmake)
```
