### ISSUE TITLE
Debug build support

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-buildtools#75]
As a follow-up of yesterday's discussion, I would like to clarify what is needed to provide support for deubg builds and products in `daq-buildtools`. If I remember correctly the problems has 2 aspects

1. Provide a way to build daq packages in debug mode. Iit may be as simple as setting the right compilation flags (e.g. `-g --ggdb`). Does tht have to be done manually or does cmake understand the concept of debug build
2. Provide the support for building `debug` variant of the daq UPS packages. This may be as simple as building the packages in debug mode as described in 1) and upsify the products with the proper qualifier set (is that `debug`) or there could be other subtleties. 

Can you clarify @dingp ?

**Comment by jcfreeman2** [comment]
CMake does have a concept of debug vs. optimized builds, see, e.g. https://cmake.org/cmake/help/v3.12/variable/CMAKE_BUILD_TYPE.html

**Comment by alessandrothea** [comment]
Well spotted! Thanks @jcfreeman2

**Comment by alessandrothea** [comment]
So, how can it be made available in `daq_build_software.sh`?

**Comment by dingp** [comment]
The first step is to have proper CMake settings (or have proper daq-cmake functions) to make the debug build across all packages in the working directory.

For making the UPS products of DAQ packages, this would be enough. One would just need to create two working directories, one is dedicated for making prof build and the other for making the debug build.

However, do we plan to support having both debug and prof/optimized build under the same working directory? Other systems does allow so, e.g. MRB and SRT. If so, we will need to adjust current directory structure of the build and install area. The path to the build objects and lib area of each package does not reflect the build type. Additionally, we will need to have a mechanism in daq-cmake modules to find the correct debug or prof build of dependent libs in the working directory.

**Comment by jcfreeman2** [comment]
Four ideas for how to make debug builds available:

* Make the prof build the default, but add a `--debug` option to `build_daq_software.sh`. 
* Make the debug build the default, but add a `--prof` option 
* Provide a `--buildtype` option which takes an argument. This would leave flexibility for the future. We could still choose a default value for it
* Have users set a CMAKE_BUILD_TYPE environment variable which gets picked up by CMake

Concerning having simultaneous prof and debug builds in the same working directory: I feel like we can hold off on this, at least until giving this further thought. Issues arise like, should the debug or prof paths be prioritized by `setup_runtime_environment`? Should all build types (debug, prof, etc.) always be built? And so on.

**Comment by jcfreeman2** [comment]
I've added -O2 as a default compiler option, but now, if you add `--debug` as an argument to `dbt-build.sh`, it gets removed. We can come up with more sophisticated definitions of a "debug build" moving forward.

**Comment by alessandrothea** [comment]
Closed by #85
