### ISSUE TITLE
Standardising script and file names

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-buildtools#76]
To follow up on yesterday's discussion, I am putting here some considerations about script and filenames standardization.
Two aspects:
- dashes vs underscores: mostly aesthetic,  and yet it would be good to pick one of the two
- meaningful names: some of the scripts have evolved since their first conception other have just been misnamed (e.g. `.dunedaq_area`). It would be good to come up with some conventions and update the names accordingly such that the purpose of each of them is clear. In details:
    - `quick-start.sh`: should the name reflect that the main role of the script it to "create" a development area? quick-start is kinda generic. Random suggestion `dbt-create-area.sh`, `dbt-init-area.sh`
    - `build_daq_software.sh`: OK-ish. Random suggestion `dbt-build.sh`
    - `setup_*`: OK.
    - `.dunedaq_area`: Born to mark the root of a development area, it now contains the ups-package settings, so how about `.dbt-settings`?
    - Any other name that should be updated?

Thoughts?

**Comment by jcfreeman2** [comment]
If we want to standardize: I think it makes sense that we shouldn't mix dashes and underscores. And I'm reflecting on prefacing all our scripts with "dbt-": it will have costs, and it will have benefits. To start with the costs:

* In a standalone sense, it doesn't really improve a script's name (`build_daq_software.sh` is less awkward and conveys more than `dbt-build.sh`)
* As with any change of this nature, people have to learn a new way of accomplishing the same task, with all that implies

But the benefits:
* A user can just type "dbt"-<tab> and bash shells will literally print out all the daq-buildtools scripts
* Our names will never collide with another package's script

If we go the `dbt-` route, though, I feel we'd want to change the setup scripts as well. E.g., `setup_build_environment` would become `dbt-setup-build-environment`, etc. 

Another point: if we're going to change names, I'm not a fan of hiding `.dunedaq_area` via the period in front, given that it's something people will be frequently editing (e.g., adding zmq) and given that people can easily forget to delete it if they want to rerun quick-start.sh should something go wrong (like they ran quick-start.sh in an unclean environment)

**Comment by alessandrothea** [comment]
> If we want to standardize: I think it makes sense that we shouldn't mix dashes and underscores.

Good good

> And I'm reflecting on prefacing all our scripts with "dbt-": it will have costs, and it will have benefits. To start with the costs:
> 
> * In a standalone sense, it doesn't really improve a script's name (`build_daq_software.sh` is less awkward and conveys more than `dbt-build.sh`)

`dbt-build.sh` was not particularly thought through. Would you prefer a more verbose `dbt-build-daq-software.sh`? I have to say that the `-daq-software` bit feels kind of redundant

> * As with any change of this nature, people have to learn a new way of accomplishing the same task, with all that implies

That's always the case. Fortunately we have a sufficiently small user base that we can afford moving few things around.
In this particular case the new and the old ways differ only by the command names...

> But the benefits:
> 
> * A user can just type "dbt"- and bash shells will literally print out all the daq-buildtools scripts
> * Our names will never collide with another package's script
> 
> If we go the `dbt-` route, though, I feel we'd want to change the setup scripts as well. E.g., `setup_build_environment` would become `dbt-setup-build-environment`, etc.

Agreed.

> Another point: if we're going to change names, I'm not a fan of hiding `.dunedaq_area` via the period in front, given that it's something people will be frequently editing (e.g., adding zmq) and given that people can easily forget to delete it if they want to rerun quick-start.sh should something go wrong (like they ran quick-start.sh in an unclean environment)

The rationale for keeping `.dunedaq_area` (or `.dbt-settings`?) hidden was to somehow keep it safe from unwanted modifications or deletions. Making it visible, OK we can do that, no big deal but a) the manual addition of extra dependencies by editing `.dunedaq_area` should go away (see my comment in #62) b) can one really re-run quick-start in a dirty area? I thought not...

**Comment by jcfreeman2** [comment]
I think we're close to converging. 

* Re: `dbt-build.sh` vs. `dbt-build-daq-software.sh`: I feel like most end users won't infer any semantic meaning from the `dbt-` in front and will instead think of it as a label, and hence in terms of clarity it boils down to "build" vs. "build daq software"

* If it really is the case that `.dunedaq_area` (using the old name) won't be edited, then that strengthens the argument for keeping it hidden. Also, when `quick-start.sh` (again, using the old name) determines that the directory it's being run in isn't empty it could actually print out the contents with the `-a` option. Right now it just tells you the directory isn't empty, which could drive users nuts who ran `rm -f *` (which skips over files preceded with dots) and can't see anything in the not-empty directory via `ls`

**Comment by alessandrothea** [comment]
Cool.
* `dbt-build.sh` vs. `dbt-build-daq-software.sh`: I suspect that beyond first time users, it doesn't make much difference. Past the first moment of confusion, usually shorter is better. Up to you.
* I hope we can get to a point where it doesn't have to be edited, but no guarantees man! I like the `ls -a` as part of the `quick-start.sh` error on the failure of the empty-check test!

So, how do we do this?

**Comment by jcfreeman2** [comment]
* `dbt-build.sh` is fine
* I'll add the `ls -a` check to the error message. Here's another idea that popped into my head; take it or leave it:  (still using old names), `.dunedaq_area` gets its period removed, BUT `quick-start.sh` removes write access (`chmod 444`) on it. People may even be curious just to take a look at it + we could add a comment at its top telling people it shouldn't be edited. Should we ever decide that it should be edited, people won't need to hunt for it or know about `ls -a`, plus we can remove the `chmod 444` and the do-not-edit-this comment.
