### ISSUE TITLE
Should daq-buildtools allow users to have the current directory as part of their path?

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#80]
Some users may have their current directory (`.`) as part of their `PATH` environment variable. If this is the case, and they try to run `dbt-create.sh --list`, the following appears:
```
find: The current directory is included in the PATH environment variable, which is insecure in combination with the -execdir action of find.  Please remove the current directory from your $PATH (that is, remove ".", doubled colons, or leading or trailing colons)
```
It's a bit awkward/cumbersome to remove the `.` from `PATH`, and while a user could edit their `.bash_profile` to remove it, it's possible they have other scripts on unrelated projects which assume that it's there. It's worth considering removing the de-facto requirement that users remove `.` from their `PATH` in order for `daq-buildtools` to be fully functional.

**Comment by alessandrothea** [comment]
I'm not sure I understand how the problem manifests itself: does it amount to `find` printing a warning message or does it actually refuse to run? 

Regarding `.` in `PATH` I tend to agree with `find`, but that's a detail. Surely the release discovery logic that uses `find` can be modified to obtain the same result without it. Alternatively locally modifying `PATH` to remove `.` is easy enough.

**Comment by alessandrothea** [comment]
Useful read on risks associated with having relative directories in `PATH`
https://askubuntu.com/questions/621132/why-is-using-the-execdir-action-insecure-for-directory-which-is-in-the-path

**Comment by jcfreeman2** [comment]
Closing this thanks to Alessandro's PR 82
