### ISSUE TITLE
clang  package not found under dunedaq_v2.1.0 release

### ISSUE THREAD

**Issue by carloschavez** [DUNE-DAQ/daq-buildtools#89]
When I trying to use "clang" package from the DUNE products  under release  "dunedaq-v2.1.0"  it fails to find it.
This is , after adding "clang v7_0_0rc3"  to dbt-settings, and then running   dbt-setup-build-environment  I get this error :

Error encountered when setting up product: clang
ERROR: Product 'clang' (with qualifiers ''), has no v7_0_0rc3 version (or may not exist)

My guess is that something needs updating in ..../DUNE/products/clang/v7_0_0rc3/ups/clang.table

Under release "dunedaq-v2.0.0"  adding "clang v7_0_0rc3" to .dunedaq_area  works fine, and it does not matter if the qualifiers "e19:prof"  are included or not,  the outcome is the same.

**Comment by dingp** [comment]
Adding `/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products` to the `products_dir` in `dbt-settings` file will fix this issue at the moment.

Starting from the next release (`dunedaq-v2.2.0`), I will have `clang` in the release directory by default.
