### ISSUE TITLE
Safeguards against common mistakes

### ISSUE THREAD

**Issue by Juravenator** [DUNE-DAQ/daq-buildtools#95]
While using the 'instructions for running the app' of minidaqapp, I noticed a couple of (sometimes silent) failures.

So I ended up with a couple of adjustments that check some basic things
- are you running a script sourced or not (depends on the script)
- using 'bash safe mode' (where possible)
- check for silent failures in product set up (this is what sparked this tinkering)
- some documentation

**Comment by Juravenator** [comment]
These changes have been pushed to the 95-common-mistakes branch.
They are intended for feedback, not to merge into master (in this state at least)

**Comment by alessandrothea** [comment]
Thanks for the input @Juravenator . Your recommended changes have been merged to develop.
