### ISSUE TITLE
Creating CI for daq-buildtools

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-buildtools#98]
We plan to trigger the CI by the following events:

1. pull request to `develop`;
2. push to `develop`;
3. periodically scheduled;
4. `dispatch` event to the repo, which allow us to trigger the CI externally (for the future);

The CI will do the following for each type of triggered events above:

1. test setup and create a work directory based on a dumb release which only requires DAQ externals with their latest versions for the incoming release;
2. same as 1
3. test setup and create the develop release (latest DAQ externals and develop version of DAQ packages);
4. same as 3.

**Comment by brettviren** [comment]
What CI system will be used?

**Comment by dingp** [comment]
Github Actions.

**Comment by dingp** [comment]
Although the release-wide nightly job in `daq-relaese` and scheduled nightly CI tests in each DAQ package's repo uses dbt, but it was the latest tagged `dbt`.

So this proposed CI workflow is still good-to-have. However it is hard to implement since changes to dbt is very likely disruptive and the docker container for CI jobs could not be used. It will be less troublesome if the CI jobs are dispatched to self-hosted servers with cvmfs access. But running on self-hosted servers implies changing the repo to from public to private. Not sure if we want to do that yet.

**Comment by dingp** [comment]
Closing the issue. Since most if not all of dbt changes should be tested interactively.
